Add support for POST on policies
HewlettPackard/simplivity-python-sdk pull request #14
Opened 2020-03-05 15:31 UTC by svt-hchaudhari

Signed-off-by: Hemant Chaudhari <hchaudhari@hpe.com>

2020-03-06 13:39 UTC, svt-kmcdaniel requested changes

2020-03-06 13:39 UTC, svt-kmcdaniel commented on examples/policies.py
> +policies.create(policy_name)
should we use the return from policies.create to delete the policy?

That will ensure that we are deleting the policy that was created.

2020-03-06 13:39 UTC, svt-kmcdaniel commented on simplivity/resources/policies.py
> +        return self._client.do_post(URL, data, timeout, None, flags)
Are you sure that do_post returns a policy object?

I thought do_post returns a list of affected objects.

2020-03-06 13:39 UTC, svt-kmcdaniel commented on tests/unit/resources/test_policies.py
> +        self.policies.create(policy_name)
need to ensure that policies.create() returns a Policy object within the unit tests

2020-03-08 19:03 UTC, svt-hchaudhari commented on examples/policies.py
> +policies.create(policy_name)
Yes made the respective changes to get the list of policies and then retrieving the required policy object to delete the same.

2020-03-08 19:05 UTC, svt-hchaudhari commented on simplivity/resources/policies.py
> +        return self._client.do_post(URL, data, timeout, None, flags)
You are right it does returns the affected objects and from there we shall retrieve the policy object and send it back as part of policies.

2020-03-08 19:06 UTC, svt-hchaudhari commented on tests/unit/resources/test_policies.py
> +        self.policies.create(policy_name)
Agreed, made the respective changes.

2020-03-08 19:40 UTC, closed without merging