Add support for feature restore files from backup
HewlettPackard/simplivity-python-sdk pull request #78
Opened 2020-06-23 18:07 UTC by svt-pchavan

Signed-off-by: pratiksha chavan <pratiksha.chavan@hpe.com>

### Description
Add support for feature restore files from backup

### Issues Resolved
None

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass(`$ tox`).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
  - [ ] New endpoints supported are updated in the endpoints-support.md file.
- [ ] Changes are documented in the CHANGELOG.

2020-06-24 15:11 UTC, svt-pchavan commented
Updated the content-type to minimum version from were the API is supported

2020-08-06 09:03 UTC, sijeesh requested changes

2020-08-06 09:03 UTC, sijeesh commented on examples/backups.py
> +    backup.restore_files(target_vm_id, paths)
I think we should give this feature to the vm resource also to restore from its backup.
Eg. vm.restore(back_up_name) 

What's your opinion on this?

2020-08-07 13:46 UTC, svt-pchavan commented on examples/backups.py
> +    backup.restore_files(target_vm_id, paths)
Yes but the only thing is, there is no direct API for restore functionality under VM resource. We have '/backups/{bkpId}/restore' under backup resource which is already automated.

2020-08-27 04:23 UTC, sijeesh commented
@svt-pchavan , please resolve the conflicts.

2020-09-08 10:49 UTC, sijeesh approved these changes
LGTM

2020-09-08 10:49 UTC, merged