Fix for exception  thrown from connection.py if resp_body is None or empty from method do_http
HewlettPackard/simplivity-python-sdk pull request #82
Opened 2020-06-29 14:20 UTC by svt-vverma

### Description
Fix for exception  thrown from connection.py if resp_body is None or empty from method do_http

### Issues Resolved
Fixes #81 

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass(`$ tox`).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
  - [ ] New endpoints supported are updated in the endpoints-support.md file.
- [ ] Changes are documented in the CHANGELOG.

2020-08-06 08:44 UTC, sijeesh requested changes

2020-08-06 08:44 UTC, sijeesh commented on simplivity/connection.py
> +            if resp_body:
lets add a test case for null response

2020-08-14 14:27 UTC, svt-vverma commented on simplivity/connection.py
> +            if resp_body:
test case added as per suggestion

2020-08-27 04:30 UTC, sijeesh approved these changes
LGTM

2020-08-27 04:30 UTC, merged