Add support to get virtual machine metrics
HewlettPackard/simplivity-python-sdk pull request #86
Opened 2020-07-06 18:09 UTC by svt-hchaudhari

Signed-off-by: Hemant Chaudhari <hchaudhari@hpe.com>

### Description
Add support to get virtual machine metrics

### Issues Resolved
None

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass(`$ tox`).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
  - [ ] New endpoints supported are updated in the endpoints-support.md file.
- [ ] Changes are documented in the CHANGELOG.

2020-08-06 07:56 UTC, sijeesh requested changes

2020-08-06 07:56 UTC, sijeesh commented on endpoints-support.md
> +|<sub>/hosts</sub>                                                                           |GET     |
duplicate entries

2020-08-06 12:49 UTC, svt-hchaudhari commented on endpoints-support.md
> +|<sub>/hosts</sub>                                                                           |GET     |
Removed the duplicate entries.

2020-08-07 09:44 UTC, sijeesh approved these changes

2020-08-07 09:47 UTC, merged